//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designer_Taus
    {
        public System.Guid UserID { get; set; }
        public string TausID { get; set; }
        public string TausName { get; set; }
        public string DesignerType { get; set; }
        public Nullable<double> RetailMultiplier { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> RateDefault { get; set; }
    }
}
