//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Item_InStockProgram = new HashSet<Item_InStockProgram>();
            this.Item_ShippingStatus = new HashSet<Item_ShippingStatus>();
            this.Lookbook_Item = new HashSet<Lookbook_Item>();
            this.Order_Item = new HashSet<Order_Item>();
            this.RelatedSkuForSpecialGroups = new HashSet<RelatedSkuForSpecialGroup>();
            this.SKUListingForSizeAvailabilities = new HashSet<SKUListingForSizeAvailability>();
            this.C2Dfeature = new HashSet<C2Dfeature>();
            this.C3Dfeature = new HashSet<C3Dfeature>();
            this.Cares = new HashSet<Care>();
            this.Centuries = new HashSet<Century>();
            this.ColourAndFinishes = new HashSet<ColourAndFinish>();
            this.Geographies = new HashSet<Geography>();
            this.HistoricalStyles = new HashSet<HistoricalStyle>();
            this.KenoVideos = new HashSet<KenoVideo>();
            this.ProcessAndTechniques = new HashSet<ProcessAndTechnique>();
            this.Shapes = new HashSet<Shape>();
            this.Countries = new HashSet<Country>();
            this.Item1 = new HashSet<Item>();
            this.Items = new HashSet<Item>();
            this.ExclusivityGroups = new HashSet<ExclusivityGroup>();
            this.Item_Fabric = new HashSet<Item_Fabric>();
            this.ShoppingCart_Item = new HashSet<ShoppingCart_Item>();
        }
    
        public System.Guid ID { get; set; }
        public string SKU { get; set; }
        public string URLCode { get; set; }
        public Nullable<decimal> CMSideAndFrontRailApronClearance { get; set; }
        public Nullable<decimal> CMSlatToTopOfSideRailClearance { get; set; }
        public Nullable<decimal> CMSlatToTopOfFootRailClearance { get; set; }
        public Nullable<decimal> INCHSideAndFrontRailApronClearance { get; set; }
        public Nullable<decimal> INCHSlatToTopOfSideRailClearance { get; set; }
        public Nullable<decimal> INCHSlatToTopOfFootRailClearance { get; set; }
        public string INCHSideAndFrontRailApronClearanceString { get; set; }
        public string INCHSlatToTopOfSideRailClearanceString { get; set; }
        public string INCHSlatToTopOfFootRailClearanceString { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Story { get; set; }        
        public string VariationDescription { get; set; }
        public string ExtendedDescription { get; set; }
        public string AdditionalFeatures { get; set; }
        public string ParentCode { get; set; }
        public string DefaultCode { get; set; }
        public string Shipping { get; set; }
        public Nullable<System.Guid> Designer_ID { get; set; }
        public Nullable<System.Guid> LifeStyle_ID { get; set; }
        public Nullable<System.Guid> Style_ID { get; set; }
        public Nullable<System.Guid> Type_ID { get; set; }
        public Nullable<System.Guid> RoomAndUsage_ID { get; set; }
        public System.Guid Brand_ID { get; set; }
        public Nullable<System.Guid> Collection_ID { get; set; }
        public Nullable<System.Guid> PrimaryMaterial_ID { get; set; }
        public Nullable<System.Guid> SecondaryMaterial_ID { get; set; }
        public Nullable<System.Guid> TertiaryMaterial_ID { get; set; }
        public string Keywords { get; set; }
        public Nullable<System.Guid> OptionGroup_ID { get; set; }
        public Nullable<System.Guid> OptionGroup2_ID { get; set; }
        public Nullable<System.Guid> OptionGroup3_ID { get; set; }
        public bool HasOtherSizes { get; set; }
        public Nullable<double> CBM { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> ChairSeatHeight { get; set; }
        public Nullable<decimal> ChairArmHeight { get; set; }
        public Nullable<decimal> ChairInsideSeatDepth { get; set; }
        public Nullable<decimal> ChairInsideSeatWidth { get; set; }
        public Nullable<System.Guid> MatchingArmOrSide { get; set; }
        public Nullable<decimal> TableClearance { get; set; }
        public Nullable<decimal> TableClosedDepth { get; set; }
        public Nullable<decimal> TableClosedWidth { get; set; }
        public Nullable<decimal> TableClosedHeight { get; set; }
        public Nullable<int> TableLeavesCount { get; set; }
        public Nullable<decimal> TableLeavesWidth { get; set; }
        public Nullable<int> TablesSeatsCountClosed { get; set; }
        public Nullable<int> TablesSeatsCountOpen { get; set; }
        public Nullable<bool> IsBestSeller { get; set; }
        public Nullable<bool> IsUpholsteredBack_WoodBack { get; set; }
        public Nullable<bool> Extending { get; set; }
        public Nullable<bool> Nail { get; set; }
        public Nullable<bool> UPHFinish { get; set; }
        public bool IsNew { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int QuantityMultiplier { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string IntroductionDate { get; set; }
        public Nullable<bool> IsStocked { get; set; }
        public Nullable<bool> IsCFPItem { get; set; }
        public Nullable<bool> IsAXHCFPItem { get; set; }
        public Nullable<bool> InStockProgram { get; set; }
        public Nullable<bool> IsActiveINTL { get; set; }
        public Nullable<bool> IsActiveTAUS { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Collection Collection { get; set; }
        public virtual Designer Designer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_InStockProgram> Item_InStockProgram { get; set; }
        public virtual Material Material { get; set; }
        public virtual Material Material1 { get; set; }
        public virtual Material Material2 { get; set; }
        public virtual OptionGroup OptionGroup { get; set; }
        public virtual OptionGroup OptionGroup1 { get; set; }
        public virtual OptionGroup OptionGroup2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_ShippingStatus> Item_ShippingStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lookbook_Item> Lookbook_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Item> Order_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelatedSkuForSpecialGroup> RelatedSkuForSpecialGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SKUListingForSizeAvailability> SKUListingForSizeAvailabilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C2Dfeature> C2Dfeature { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C3Dfeature> C3Dfeature { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Care> Cares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Century> Centuries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ColourAndFinish> ColourAndFinishes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Geography> Geographies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoricalStyle> HistoricalStyles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KenoVideo> KenoVideos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessAndTechnique> ProcessAndTechniques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shape> Shapes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Country> Countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Item1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
        public virtual LifeStyle LifeStyle { get; set; }
        public virtual RoomAndUsage RoomAndUsage { get; set; }
        public virtual Style Style { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExclusivityGroup> ExclusivityGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_Fabric> Item_Fabric { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart_Item> ShoppingCart_Item { get; set; }
    }
}
