//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookbook_Item
    {
        public System.Guid Lookbook_ID { get; set; }
        public System.Guid Item_ID { get; set; }
        public string Note { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual Lookbook Lookbook { get; set; }
        public virtual Item Item { get; set; }
    }
}
