//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public System.Guid ID { get; set; }
        public System.Guid OptionGroup_ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Filename { get; set; }
    
        public virtual OptionGroup OptionGroup { get; set; }
    }
}
