//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Item = new HashSet<Order_Item>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid Dealer_ID { get; set; }
        public int OrderNumber { get; set; }
        public System.DateTime DateSubmitted { get; set; }
        public string ShippingAddress1 { get; set; }
        public string ShippingAddress2 { get; set; }
        public System.Guid ShippingCity_ID { get; set; }
        public string ShippingPostalCode { get; set; }
        public string ShippingPhone { get; set; }
        public string ContainerReference { get; set; }
        public string ShippingInstructions { get; set; }
    
        public virtual City City { get; set; }
        public virtual Dealer Dealer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Item> Order_Item { get; set; }
    }
}
