//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_Item()
        {
            this.Order_Item_ShippingStatus = new HashSet<Order_Item_ShippingStatus>();
        }
    
        public System.Guid Order_ID { get; set; }
        public System.Guid Item_ID { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Item_ShippingStatus> Order_Item_ShippingStatus { get; set; }
        public virtual Item Item { get; set; }
    }
}
