//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Item_ShippingStatus
    {
        public System.Guid Order_ID { get; set; }
        public System.Guid Item_ID { get; set; }
        public System.Guid ShippingStatus_ID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Order_Item Order_Item { get; set; }
        public virtual ShippingStatu ShippingStatu { get; set; }
    }
}
