//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile_ItemPrice
    {
        public string SKU { get; set; }
        public string ProfileType { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> CPPrice { get; set; }
        public Nullable<decimal> TotalCPPrice { get; set; }
    }
}
