//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesAssociate
    {
        public System.Guid ID { get; set; }
        public System.Guid User_ID { get; set; }
    
        public virtual SalesAssociate_Store SalesAssociate_Store { get; set; }
        public virtual User User { get; set; }
    }
}
