//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesAssociate_Store
    {
        public System.Guid SalesAssociate_ID { get; set; }
        public System.Guid Store_ID { get; set; }
        public bool DealerApproved { get; set; }
    
        public virtual SalesAssociate SalesAssociate { get; set; }
        public virtual Store Store { get; set; }
    }
}
