//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Search
    {
        public System.Guid ID { get; set; }
        public string SKU { get; set; }
        public string ProductName { get; set; }
        public string Story { get; set; }
        public string VariationDescription { get; set; }
        public string ExtendedDescription { get; set; }
        public string AdditionalFeatures { get; set; }
        public string LifeStyle { get; set; }
        public string RoomAndUsage { get; set; }
        public string Brand { get; set; }
        public string Collection { get; set; }
        public string Keywords { get; set; }
        public string ParentCode { get; set; }
        public string DefaultCode { get; set; }
        public string PrimaryMaterial { get; set; }
        public string SecondaryMaterial { get; set; }
        public string TertiaryMaterial { get; set; }
        public string OptionGroup { get; set; }
        public string OptionGroup2 { get; set; }
        public string OptionGroup3 { get; set; }
        public string C2Dfeatures { get; set; }
        public string C3Dfeatures { get; set; }
        public string Cares { get; set; }
        public string Centuries { get; set; }
        public string ColourAndFinishes { get; set; }
        public string Geographies { get; set; }
        public string ProcessAndTechniques { get; set; }
        public string Shapes { get; set; }
        public string Style { get; set; }
        public string Designer { get; set; }
        public string HistoricalStyles { get; set; }
        public string Type { get; set; }
        public string AllInclusive { get; set; }
    }
}
