//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchStore
    {
        public System.Guid ID { get; set; }
        public string StoreName { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<decimal> CityLongitude { get; set; }
        public Nullable<decimal> CityLatitude { get; set; }
        public string CityName { get; set; }
        public string RegionName { get; set; }
        public string CountryName { get; set; }
        public string ContinentName { get; set; }
    }
}
