//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShippingStatu()
        {
            this.Item_ShippingStatus = new HashSet<Item_ShippingStatus>();
            this.Order_Item_ShippingStatus = new HashSet<Order_Item_ShippingStatus>();
            this.ShoppingCart_Item_ShippingStatus = new HashSet<ShoppingCart_Item_ShippingStatus>();
        }
    
        public System.Guid ID { get; set; }
        public string DeliveryTime { get; set; }
        public string DeliveryState { get; set; }
        public int MinimumDelay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_ShippingStatus> Item_ShippingStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Item_ShippingStatus> Order_Item_ShippingStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart_Item_ShippingStatus> ShoppingCart_Item_ShippingStatus { get; set; }
    }
}
