//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShoppingCart_Item()
        {
            this.ShoppingCart_Item_ShippingStatus = new HashSet<ShoppingCart_Item_ShippingStatus>();
        }
    
        public System.Guid ShoppingCart_ID { get; set; }
        public System.Guid Item_ID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ShoppingCart ShoppingCart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart_Item_ShippingStatus> ShoppingCart_Item_ShippingStatus { get; set; }
    }
}
