//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKUListingForSizeAvailability
    {
        public System.Guid ID { get; set; }
        public System.Guid Item_ID { get; set; }
        public string SKU { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
