//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreCoordinate
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> Store_ID { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public string Address { get; set; }
        public string GoogleAddress { get; set; }
        public string GoogleUrl { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
