//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.SalesAssociate_Store = new HashSet<SalesAssociate_Store>();
            this.StoreCoordinates = new HashSet<StoreCoordinate>();
            this.Dealers = new HashSet<Dealer>();
            this.Brands = new HashSet<Brand>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public double PriceMultiplier { get; set; }
        public Nullable<double> PriceMultiplierTAS { get; set; }
        public bool AccountEnabled { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsPreferred { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public System.Guid City_ID { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool IsAlthorpLivingHistory { get; set; }
        public bool IsAlexaHampton { get; set; }
        public bool IsUpholstery { get; set; }
        public bool IsTAStudio { get; set; }
        public bool IsSalone { get; set; }
        public bool IsRalphLauren { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string GoogleUrl { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesAssociate_Store> SalesAssociate_Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreCoordinate> StoreCoordinates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dealer> Dealers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Brand> Brands { get; set; }
    }
}
