//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCollection
    {
        public System.Guid Collection_ID { get; set; }
        public Nullable<System.Guid> Brand_ID { get; set; }
        public Nullable<System.Guid> ParentCollection_ID { get; set; }
    
        public virtual Collection Collection { get; set; }
    }
}
