//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TheodoreAlexanderEntities : DbContext
    {
        public TheodoreAlexanderEntities()
            : base("name=TheodoreAlexanderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C2Dfeature> C2Dfeature { get; set; }
        public virtual DbSet<C3Dfeature> C3Dfeature { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Care> Cares { get; set; }
        public virtual DbSet<Century> Centuries { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Collection> Collections { get; set; }
        public virtual DbSet<ColourAndFinish> ColourAndFinishes { get; set; }
        public virtual DbSet<Continent> Continents { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CountryBlackList> CountryBlackLists { get; set; }
        public virtual DbSet<Dealer> Dealers { get; set; }
        public virtual DbSet<Dealer_Taus> Dealer_Taus { get; set; }
        public virtual DbSet<DealerGroup_Region> DealerGroup_Region { get; set; }
        public virtual DbSet<DynamicTable> DynamicTables { get; set; }
        public virtual DbSet<ExclusivityGroup> ExclusivityGroups { get; set; }
        public virtual DbSet<Geography> Geographies { get; set; }
        public virtual DbSet<ImageExistingStatu> ImageExistingStatus { get; set; }
        public virtual DbSet<IPBlackList> IPBlackLists { get; set; }
        public virtual DbSet<IPWhiteList> IPWhiteLists { get; set; }
        public virtual DbSet<Item_CFP> Item_CFP { get; set; }
        public virtual DbSet<Item_InStockProgram> Item_InStockProgram { get; set; }
        public virtual DbSet<Item_Price> Item_Price { get; set; }
        public virtual DbSet<Item_ShippingStatus> Item_ShippingStatus { get; set; }
        public virtual DbSet<Item_Status> Item_Status { get; set; }
        public virtual DbSet<Item_TAU> Item_TAU { get; set; }
        public virtual DbSet<KenoVideo> KenoVideos { get; set; }
        public virtual DbSet<Lookbook> Lookbooks { get; set; }
        public virtual DbSet<Lookbook_Item> Lookbook_Item { get; set; }
        public virtual DbSet<LookbookShared> LookbookShareds { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<MaterialCategory> MaterialCategories { get; set; }
        public virtual DbSet<Option> Options { get; set; }
        public virtual DbSet<OptionGroup> OptionGroups { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Order_Item> Order_Item { get; set; }
        public virtual DbSet<Order_Item_ShippingStatus> Order_Item_ShippingStatus { get; set; }
        public virtual DbSet<ProcessAndTechnique> ProcessAndTechniques { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<RelatedSkuForSpecialGroup> RelatedSkuForSpecialGroups { get; set; }
        public virtual DbSet<SalesAssociate> SalesAssociates { get; set; }
        public virtual DbSet<SalesAssociate_Store> SalesAssociate_Store { get; set; }
        public virtual DbSet<Shape> Shapes { get; set; }
        public virtual DbSet<ShippingStatu> ShippingStatus { get; set; }
        public virtual DbSet<ShoppingCart_Item_ShippingStatus> ShoppingCart_Item_ShippingStatus { get; set; }
        public virtual DbSet<SKUListingForSizeAvailability> SKUListingForSizeAvailabilities { get; set; }
        public virtual DbSet<SubCollection> SubCollections { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<CollectionBlackout> CollectionBlackouts { get; set; }
        public virtual DbSet<ExclusivityException> ExclusivityExceptions { get; set; }
        public virtual DbSet<SearchStore> SearchStores { get; set; }
        public virtual DbSet<Designer> Designers { get; set; }
        public virtual DbSet<Item_OptionDescription> Item_OptionDescription { get; set; }
        public virtual DbSet<Item_Icon> Item_Icon { get; set; }
        public virtual DbSet<HistoricalStyle> HistoricalStyles { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<StoreCoordinate> StoreCoordinates { get; set; }
        public virtual DbSet<LifeStyle> LifeStyles { get; set; }
        public virtual DbSet<RoomAndUsage> RoomAndUsages { get; set; }
        public virtual DbSet<Style> Styles { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<UPHColour> UPHColours { get; set; }
        public virtual DbSet<UPHPattern> UPHPatterns { get; set; }
        public virtual DbSet<Search> Searches { get; set; }
        public virtual DbSet<SubcribedEmail> SubcribedEmails { get; set; }
        public virtual DbSet<Designer_Taus> Designer_Taus { get; set; }
        public virtual DbSet<Profile_ItemPrice> Profile_ItemPrice { get; set; }
        public virtual DbSet<UPHContent> UPHContents { get; set; }
        public virtual DbSet<ItemResourceFile> ItemResourceFiles { get; set; }
        public virtual DbSet<ItemResourceFile_Rule> ItemResourceFile_Rule { get; set; }
        public virtual DbSet<UPHFabric> UPHFabrics { get; set; }
        public virtual DbSet<Item_Fabric> Item_Fabric { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCarts { get; set; }
        public virtual DbSet<ShoppingCart_Item> ShoppingCart_Item { get; set; }
    
        [DbFunction("TheodoreAlexanderEntities", "udf_FreeTextSearch")]
        public virtual IQueryable<udf_FreeTextSearch_Result> udf_FreeTextSearch(string keywords)
        {
            var keywordsParameter = keywords != null ?
                new ObjectParameter("keywords", keywords) :
                new ObjectParameter("keywords", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_FreeTextSearch_Result>("[TheodoreAlexanderEntities].[udf_FreeTextSearch](@keywords)", keywordsParameter);
        }
    
        [DbFunction("TheodoreAlexanderEntities", "udf_SearchStore")]
        public virtual IQueryable<udf_SearchStore_Result> udf_SearchStore(string keywords)
        {
            var keywordsParameter = keywords != null ?
                new ObjectParameter("keywords", keywords) :
                new ObjectParameter("keywords", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_SearchStore_Result>("[TheodoreAlexanderEntities].[udf_SearchStore](@keywords)", keywordsParameter);
        }
    
        public virtual ObjectResult<usp_GetAssociatesByStoreID_Result> usp_GetAssociatesByStoreID(Nullable<System.Guid> store_ID)
        {
            var store_IDParameter = store_ID.HasValue ?
                new ObjectParameter("Store_ID", store_ID) :
                new ObjectParameter("Store_ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetAssociatesByStoreID_Result>("usp_GetAssociatesByStoreID", store_IDParameter);
        }
    
        public virtual ObjectResult<usp_GetDealerBillingAddressByUserID_Result> usp_GetDealerBillingAddressByUserID(Nullable<System.Guid> user_ID)
        {
            var user_IDParameter = user_ID.HasValue ?
                new ObjectParameter("User_ID", user_ID) :
                new ObjectParameter("User_ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDealerBillingAddressByUserID_Result>("usp_GetDealerBillingAddressByUserID", user_IDParameter);
        }
    
        public virtual ObjectResult<usp_GetDealerInformationByUserID_Result> usp_GetDealerInformationByUserID(Nullable<System.Guid> user_ID)
        {
            var user_IDParameter = user_ID.HasValue ?
                new ObjectParameter("User_ID", user_ID) :
                new ObjectParameter("User_ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDealerInformationByUserID_Result>("usp_GetDealerInformationByUserID", user_IDParameter);
        }
    
        public virtual ObjectResult<usp_GetDealerPageSettingsByUserID_Result> usp_GetDealerPageSettingsByUserID(Nullable<System.Guid> user_ID)
        {
            var user_IDParameter = user_ID.HasValue ?
                new ObjectParameter("User_ID", user_ID) :
                new ObjectParameter("User_ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDealerPageSettingsByUserID_Result>("usp_GetDealerPageSettingsByUserID", user_IDParameter);
        }
    
        public virtual ObjectResult<usp_GetDealerShippingAddressByUserID_Result> usp_GetDealerShippingAddressByUserID(Nullable<System.Guid> user_ID)
        {
            var user_IDParameter = user_ID.HasValue ?
                new ObjectParameter("User_ID", user_ID) :
                new ObjectParameter("User_ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDealerShippingAddressByUserID_Result>("usp_GetDealerShippingAddressByUserID", user_IDParameter);
        }
    
        public virtual ObjectResult<usp_GetAccountDataByUserID_Result1> usp_GetAccountDataByUserID(Nullable<System.Guid> user_ID)
        {
            var user_IDParameter = user_ID.HasValue ?
                new ObjectParameter("User_ID", user_ID) :
                new ObjectParameter("User_ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetAccountDataByUserID_Result1>("usp_GetAccountDataByUserID", user_IDParameter);
        }
    
        public virtual ObjectResult<usp_GetUserSettingsByUserID_Result> usp_GetUserSettingsByUserID(Nullable<System.Guid> user_ID)
        {
            var user_IDParameter = user_ID.HasValue ?
                new ObjectParameter("User_ID", user_ID) :
                new ObjectParameter("User_ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetUserSettingsByUserID_Result>("usp_GetUserSettingsByUserID", user_IDParameter);
        }
    }
}
