//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPHFabric
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UPHFabric()
        {
            this.Item_Fabric = new HashSet<Item_Fabric>();
        }
    
        public string Fabric { get; set; }
        public Nullable<int> Grade { get; set; }
        public string GradeStudio { get; set; }
        public string Content1 { get; set; }
        public string Content2 { get; set; }
        public string Content3 { get; set; }
        public string Content4 { get; set; }
        public string Content5 { get; set; }
        public string Content6 { get; set; }
        public string Sampled { get; set; }
        public string Color { get; set; }
        public string ColorCode { get; set; }
        public string Pattern { get; set; }
        public string PatternCode { get; set; }
        public string VRepeat { get; set; }
        public string HRepeat { get; set; }
        public string Width { get; set; }
        public string CleaningCode { get; set; }
        public string Application { get; set; }
        public string Durability { get; set; }
        public Nullable<bool> enable { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool InStock { get; set; }
        public bool IsEnabledOnWeb { get; set; }
        public bool IsCutYardage { get; set; }
        public Nullable<bool> RLC { get; set; }
        public string Name { get; set; }
        public string GradeTrim { get; set; }
        public string Category { get; set; }
        public string CategoryTrim { get; set; }
        public string Rubs { get; set; }
        public Nullable<decimal> QtyOnHand { get; set; }
        public string UM { get; set; }
        public Nullable<bool> PFP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_Fabric> Item_Fabric { get; set; }
    }
}
