//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.QuotationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Designer { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string Types { get; set; }
        public string Detail { get; set; }
        public string Item { get; set; }
        public string Category { get; set; }
        public string ExpressionTheme { get; set; }
        public string Themes { get; set; }
        public string Style { get; set; }
        public string City { get; set; }
        public string ST_Abbr { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string Rep { get; set; }
        public string DateSent2Rep { get; set; }
        public string Dealer { get; set; }
        public string DealerEmail { get; set; }
        public string DealerStore { get; set; }
        public string DateSent2Dealer { get; set; }
        public string Comment { get; set; }
        public string DateDealerContactedConsumer { get; set; }
        public string Brand { get; set; }
        public string Collection { get; set; }
        public string RoomAndUsage { get; set; }
        public string ProductType { get; set; }
        public string LifeStyle { get; set; }
        public string ProductStyle { get; set; }
    }
}
