export const environment = {
  production: false, 
  DomainURL: "http://localhost:4200/",  
  DomainDestination: "http://localhost:4200/#/",  
  APIURL: "https://api2.theodorealexander.com/",
  APITESTURL: "http://api-dev.theodorealexander.com/",
  LoginURL: "http://login.theodorealexander.com/",
  Website: "https://theodorealexander.com/",
  Images: "images",  
  Download: "Download",  
  ProductDetail: "product-detail",
  Article: "article",
  USID: "facbb4b8-9f61-46cf-8e98-e63a20145739",
  EmployeeExcelFileName: "Employee.xlsx",  
  ProvinceExcelFileName: "Province.xlsx",  
  ItemBedInfomationExcelFileName: "ItemBedInfomation.xlsx",  
  ItemExcelFileName: "Item.xlsx",  
  LoadingFile: "loading.gif",
  DialogConfigWidth: "80%",
  InitializationString: "",  
  InitializationNumber: 0, 
  AuthenticationToken: "AuthenticationToken",
  MembershipID: "MembershipID",
  DefaultSubURL: "Item",  
  UploadSuccess: "Upload success.",
  UploadNotSuccess: "Upload not success.", 
  SaveSuccess: "Save success.",
  SaveNotSuccess: "Save not success.",        
  DeleteSuccess: "Delete success.",
  DeleteNotSuccess: "Delete not success.",          
  SendMailSuccess: "Send mail success.",
  SendMailNotSuccess: "Send mail not success.", 
};

